### ISSUE TITLE
Add categories and icons for transfers

### ISSUE THREAD

**Issue by ChristallerPierre** [anacounts/app#226]
On the transfer list page (such as https://app.anacounts.com/books/1/transfers)

Display the icon of the user who created the transfer on the side of each transfer, and the icon of the recipient as well in case of reimbursement.

Could it also be possible to display the list of people (or at least how many) for which the activity has been paid, on this page ?

**Comment by Gladear** [comment]
Both ideas are great indeed.

The second one is kind of related to #163, linking it to keep it in mind.

**Comment by Gladear** [comment]
Half-fixed in #277 (not released yet, this is part of a redesign of the app)

I changed my mind as to display who created the transfer, the information needs to be optimized, there is too little space for that. The number of members is displayed for payment and incomes, and both members are displayed for reimbursement though.
